variable "VPC_ID" {}
variable "PRIVATE_SUBNETS" {}
variable "PUBLIC_SUBNETS" {}
variable "MGMT_VPC_ID" {}
variable "TAGS" {}
variable "INSTANCE_TYPE" {}
variable "GIT_USR" {}
variable "GIT_PSW" {}
variable "SSH_USR" {}
variable "SSH_PSW" {}
variable "APPLICATION_NAME" {}
variable "PORTS" {}
variable "HOSTED_ZONE_ID" {}
variable "HOSTED_ZONE_NAME" {}
variable "R_USR" {}
variable "R_PSW" {}
variable "LICENSE_KEY" {}
variable "API_KEY" {}