variable "TAGS" {}
variable "INSTANCE_TYPE" {}
variable "PRIVATE_SUBNETS" {}
variable "PUBLIC_SUBNETS" {}
variable "MGMT_VPC_ID" {}
variable "VPC_ID" {}
variable "GIT_USR"          {}
variable "GIT_PSW"          {}
variable "SSH_USR"          {}
variable "SSH_PSW"          {}
variable "HOSTED_ZONE_ID" {}
variable "HOSTED_ZONE_NAME" {}
variable "R_USR" {}
variable "R_PSW" {}