variable "DBUSER" {}
variable "DBPASS" {}
variable "VPC_ID" {}
variable "PRIVATE_SUBNETS" {}
variable "PUBLIC_SUBNETS" {}
variable "MGMT_VPC_ID" {}
variable "TAGS" {}
variable "INSTANCE_TYPE" {}
variable "PROD" {}
variable "NONPROD" {}
variable "GIT_USR" {}
variable "GIT_PSW" {}
variable HOSTED_ZONE_ID  {}
variable HOSTED_ZONE_NAME {}
